version: 0.1.0
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "sfortuna77-github"
    assignees:
      - "sfortuna77-github"
    commit-message:
      prefix: "deps"
      include: "scope"
